version: "2"
services:
  php:
    image: docker.adexos.fr/adexos/php7.2-fpm
    links:
      - db
    working_dir: /app
    volumes_from:
      - appdata
    labels:
      - traefik.enable=false
    env_file:
      - ./docker/envs/magento.env
    volumes:
      - ./docker/scripts/install.sh:/docker/install.sh
      - ./docker/config/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug-20.ini:ro
    networks:
      - default

  httpd-formation:
    image: httpd:2.4
    depends_on:
      - php
    ports:
      - 80
    volumes_from:
      - appdata
    volumes:
      - ./docker/config/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./docker/config/httpd/vhost.conf:/usr/local/apache2/conf/vhost.conf:ro
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.backend=httpd-formation
      - traefik.frontend.rule=Host:formation.docker
      - traefik.port=80
      - traefik.docker.network=traefik

  node:
    image: docker.adexos.fr/adexos/node10
    volumes_from:
      - appdata
    working_dir: /app

#  varnish:
#    image: emgag/varnish:5
#    links:
#      - httpd-formation
#    networks:
#      - default
#      - traefik
#    ports:
#      - 80
#      - 6082
#    volumes:
#      - ./docker/varnish/default.vcl:/etc/varnish/default.vcl
#    environment:
#      VARNISH_MANAGEMENT_LISTEN: 0.0.0.0:6082
#    labels:
#      - traefik.enable=true
#      - traefik.backend=varnish
#      - traefik.frontend.rule=Host:formation.docker
#      - traefik.port=80
#      - traefik.docker.network=traefik

  db:
    image: mysql:5.7
    ports:
      - 3306
    volumes_from:
      - dbdata
    env_file:
      - ./docker/envs/mysql.env
    volumes:
      - ./docker/config/mysql/mysql-secure-file.cnf:/etc/mysql/conf.d/mysql-secure-file.cnf
    labels:
      - traefik.enable=false

  pma-formation:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 80
    links:
      - db
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.backend=pma-formation
      - traefik.frontend.rule=Host:pma.formation.docker
      - traefik.port=80
      - traefik.docker.network=traefik

  appdata:
    image: tianon/true
    volumes:
      - ./htdocs:/app

  dbdata:
    image: tianon/true
    volumes:
      - ./data/mysql:/var/lib/mysql

networks:
  traefik:
    external:
      name: traefik
  default: